### ISSUE TITLE
hashicorp_vault provider panic: interface conversion: interface {} is nil, not map[string]interface {} 

### ISSUE THREAD

**Issue by egargale** [bbl/secretize#3]
Thank for this plugin ! I am trying to use it in connection with Hashicorp Vault. It works fine with ENV.
With Hashicorp Vault I have the following error:
```panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/bbl/kustomize-secrets/internal/providers.(*HashicorpVaultProvider).GetSecret.func1(0xc000157e60, 0x17, 0xc000157e60, 0x17, 0xc000157e78)
	/github/workspace/internal/providers/hashicorp_vault.go:59 +0x244
github.com/bbl/kustomize-secrets/internal/providers.getKVSecret(0xc000157e60, 0x1b, 0xc00021fcc8, 0x1, 0xc0003a6cf0, 0xc00021fcd8, 0x40f16d)
	/github/workspace/internal/providers/hashicorp_vault.go:42 +0x97
github.com/bbl/kustomize-secrets/internal/providers.(*HashicorpVaultProvider).GetSecret(0xc0003ad150, 0xc000157e60, 0x1b, 0x137e9c0, 0xc000159f01, 0xc0003ad150, 0xc00021fd68)
	/github/workspace/internal/providers/hashicorp_vault.go:53 +0x61
github.com/bbl/kustomize-secrets/pkg/generator.FetchProviderSecrets(0x17c83a0, 0xc0003ad150, 0xc0003ad060, 0x1, 0x1, 0xc000376f00, 0x2, 0x2, 0x101, 0x2195de0, ...)
	/github/workspace/pkg/generator/generator.go:101 +0xb6
github.com/bbl/kustomize-secrets/pkg/generator.(*SecretGenerator).FetchSecrets(0xc000137f20, 0x155d8a0, 0x2f9, 0xc000137f20, 0x0)
	/github/workspace/pkg/generator/generator.go:88 +0x192
main.main()
	/github/workspace/cmd/secretize/main.go:28 +0x1a7
Error: failure in plugin configured via /tmp/kust-plugin-config-342364564; exit status 2: exit status 2
```
The yaml file is:
```apiVersion: secretize/v1
kind: SecretGenerator
metadata:
  name: hashicorp-vault-secrets
sources:
    - provider: hashicorp-vault
      literals:
         - kv-v1/eng/apikey/Google:key
         - explicitName=kv-v1/eng/apikey/Google:key
      kv:
         - kv-v1/eng/apikey/Google
```
The command **vault kv get kv-v1/eng/apikey/Google** works, result is:

```=== Data ===
Key    Value
---    -----
key    AAaaBBccDDeeOTXzSMT1234BB_Z8JzG7JkSVxI
```
I tried both user token + policy and root token. Vault CLI works not the plugin.  

I see a warning in the documentation
```  you need to specify the full path in hashicorp vault provider```
but I do not know how to specify differently.

Vault version is v1.5.5 (f5d1ddb3750e7c28e25036e1ef26a4c02379fc01)
Kustomize version is v3.8.8

**Comment by egargale** [comment]
UPDATE. 
It works with KV version 2. The issue is limited to KV version 1.

Yaml file:
````
apiVersion: secretize/v1
kind: SecretGenerator
metadata:
  name: hashicorp-vault-secrets
sources:
    - provider: hashicorp-vault
      kv:
        - secrets/data/customer/acme
```
Secret generated
```
apiVersion: v1
data:
  contact_email: anNtaXRoQGFjbWUuY29t
  name: QUNNRSBJbmMu
kind: Secret
metadata:
  name: hashicorp-vault-secrets
```
Vault CLI command **vault kv get secrets/customer/acme**
Response:
```
====== Metadata ======
Key              Value
---              -----
created_time     2020-12-23T13:24:27.358083703Z
deletion_time    n/a
destroyed        false
version          1

======== Data ========
Key              Value
---              -----
contact_email    jsmith@acme.com
name             ACME Inc.
```
**NOTE** the difference in path between CLI and plugin due to the new KV v2 API
CLI --------------->  secrets/customer/acme
Plugin; -----------> secrets/data/customer/acme
[source](https://www.reddit.com/r/golang/comments/9ryrma/need_help_using_vault_go_client/)

**Comment by bbl** [comment]
@egargale appreciate your feedback.
Yes, the vault plugin supports only the kv2 version for now. I should've mentioned this in docs.

I can add the kv1 support if needed.

**Comment by egargale** [comment]
@bbl  Thank for your piece of software. I can move to kv2.
